name: essential-plugin
version: '1.0-SNAPSHOT'
main: de.minedesso.essentialplugin.EssentialPlugin
api-version: '1.21'
commands:
  warp:
    description: Teleport to a predefined location.
    usage: /warp <location>
  warps:
    description: List all available warp locations.
    usage: /warps
  inv:
    description: View another player's inventory.
    usage: /inv <player>
    aliases: [ec]
  home:
    description: Teleport to your home location.
    usage: /home
    aliases: [sethome, delhome, homes]
  pay:
    description: Pay another player some money.
    usage: /pay <player> <amount>
